[build]
  command = "npm run build"
  publish = "dist" 

[dev]
  command = "npm start" 
  port = 3000 


[settings]
  # Define environment variables for your 
  SPOTIFY_CLIENT_ID = "${SPOTIFY_CLIENT_ID}"
  SPOTIFY_CLIENT_SECRET = "${SPOTIFY_CLIENT_SECRET}"
  SPOTIFY_CALLBACK_URL = "${SPOTIFY_CALLBACK_URL}"
  BASE64_AUTHORIZATION = "${BASE64_AUTHORIZATION}"
  SESSION_SECRET = "${SESSION_SECRET}"