[build]
  command: npm run build
  commandOrigin: config


[settings]
  # Define environment variables for your 
  - BASE64_AUTHORIZATION
  - PORT
  - SESSION_SECRET
  - SPOTIFY_CALLBACK_URL
  - SPOTIFY_CLIENT_ID
  - SPOTIFY_CLIENT_SECRET